vich_uploader:
    db_driver: orm

    mappings:
       partner_image:
           uri_prefix: /uploads/partners
           upload_destination: '%kernel.project_dir%/public/uploads/partners'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
           
       event_image:
           uri_prefix: /uploads/event
           upload_destination: "%kernel.project_dir%/public/uploads/event"
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute
